param([switch]$UpdateOnly)
$ErrorActionPreference='Stop'
$Repo='Bendemen-Studios/HVMC';$Branch='main'
$MinecraftDir=Join-Path $env:APPDATA '.minecraft';$Root=Join-Path $env:LOCALAPPDATA 'Bendemen\HVMC'
$StatePath=Join-Path $Root 'state.json';$ManagedPath=Join-Path $Root 'managed-files.json';$LogPath=Join-Path $Root 'bootstrapper.log'
$PoolConfigPath=Join-Path $Root 'pool.json';$McVersion='1.21.11';$FabricLoader='0.18.1'
foreach($d in @($Root,$MinecraftDir,$MinecraftDir+'\mods',$MinecraftDir+'\config',$MinecraftDir+'\resourcepacks',$MinecraftDir+'\shaderpacks',$MinecraftDir+'\datapacks',$MinecraftDir+'\kubejs')){New-Item -ItemType Directory -Force -Path $d|Out-Null}
function Write-Log([string]$m){try{Add-Content -LiteralPath $LogPath -Value (("{0:u} {1}"-f(Get-Date),$m))-Encoding UTF8}catch{};Write-Host "[HVMC] $m"}
function Gh([string]$p){Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/contents/$p?ref=$Branch" -Headers @{'User-Agent'='HVMC-Updater'} -TimeoutSec 30}
function Download([string]$u,[string]$d){$parent=Split-Path -Parent $d;New-Item -ItemType Directory -Force -Path $parent|Out-Null;$tmp="$d.download";try{Invoke-WebRequest -Uri $u -OutFile $tmp -Headers @{'User-Agent'='HVMC-Updater'} -UseBasicParsing -TimeoutSec 180;if(!(Test-Path $tmp)){throw 'download failed'};Move-Item $tmp $d -Force;return $true}catch{Remove-Item $tmp -Force -ErrorAction SilentlyContinue;Write-Log "Download failed: $u :: $($_.Exception.Message)";return $false}}
function ReadJson([string]$p){if(Test-Path $p){try{return Get-Content $p -Raw|ConvertFrom-Json}catch{}};return $null}
function SaveJson($o,[string]$p){$o|ConvertTo-Json -Depth 20|Set-Content $p -Encoding UTF8}
function Safe([string]$p){$p=$p.Replace('/','\');if([IO.Path]::IsPathRooted($p)-or $p.Contains('..')){throw "Unsafe path: $p"};$p}
function SyncTree([string]$remote,[string]$local,[System.Collections.Generic.List[string]]$tracked){$items=@(Gh $remote);foreach($i in $items){if($i.type -eq 'dir'){SyncTree ([string]$i.path) $local $tracked}elseif($i.type -eq 'file'){ $rel=Safe ([string]$i.path).Substring(8);$dest=Join-Path $local $rel;$same=$false;if(Test-Path $dest){try{$same=((Get-Item $dest).Length -eq [int64]$i.size)}catch{}};if(!$same){if(!(Download ([string]$i.download_url) $dest)){throw "Unable to download $rel"};Write-Log "Updated: $rel"}else{Write-Log "Unchanged: $rel"};$tracked.Add($rel)}}}
function CleanupOld([string[]]$old,[string[]]$new){$set=@{};foreach($x in $new){$set[$x.ToLowerInvariant()]=$true};foreach($x in $old){if(!$set.ContainsKey($x.ToLowerInvariant())){$p=Join-Path $MinecraftDir (Safe $x);if(Test-Path $p){try{Remove-Item $p -Force;Write-Log "Removed obsolete managed file: $x"}catch{Write-Log "Could not remove obsolete file $x: $($_.Exception.Message)"}}}}}
function TestLauncher{$paths=@((Join-Path ${env:ProgramFiles(x86)} 'Minecraft Launcher\MinecraftLauncher.exe'),(Join-Path $env:ProgramFiles 'Minecraft Launcher\MinecraftLauncher.exe'),(Join-Path $env:LOCALAPPDATA 'Programs\Minecraft Launcher\MinecraftLauncher.exe'));foreach($p in $paths){if($p-and(Test-Path $p)){return $p}};return $null}
function EnsureLauncher{$p=TestLauncher;if($p){Write-Log 'Official Minecraft Launcher gevonden.';return $p};Write-Log 'Official Minecraft Launcher niet gevonden.';$w=Get-Command winget.exe -ErrorAction SilentlyContinue;if($w){try{&$w.Source install --id Mojang.MinecraftLauncher --exact --silent --accept-package-agreements --accept-source-agreements|Out-Null}catch{Write-Log "WinGet install failed: $($_.Exception.Message)"};$p=TestLauncher;if($p){Write-Log 'Official Minecraft Launcher geïnstalleerd.';return $p}};Start-Process 'https://www.minecraft.net/download';throw 'Official Minecraft Launcher kon niet automatisch worden geïnstalleerd.'}
function EnsureFabric{$target=Join-Path $MinecraftDir "versions\fabric-loader-$FabricLoader-$McVersion\fabric-loader-$FabricLoader-$McVersion.json";if(Test-Path $target){Write-Log "Fabric $FabricLoader voor $McVersion gevonden.";return};Write-Log "Fabric $FabricLoader voor $McVersion installeren...";$meta=Invoke-RestMethod -Uri 'https://meta.fabricmc.net/v2/versions/installer' -Headers @{'User-Agent'='HVMC-Updater'} -TimeoutSec 30;$ins=$meta|Where-Object{$_.stable -eq $true-and$_.exe}|Select-Object -First 1;if(!$ins){throw 'Geen stabiele Fabric installer gevonden.'};$ip=Join-Path $Root 'fabric-installer.exe';if(!(Download ([string]$ins.exe) $ip)){throw 'Fabric installer download mislukt.'};$proc=Start-Process $ip -ArgumentList 'client','-dir',('"'+$MinecraftDir+'"'),'-mcversion',$McVersion,'-loader',$FabricLoader -Wait -PassThru;if($proc.ExitCode-ne 0 -or !(Test-Path $target)){throw 'Fabric installatie mislukt.'};Write-Log 'Fabric installatie voltooid.'}
Write-Log 'HVMC updater gestart.'
try{$remoteVersion=([string](Invoke-RestMethod -Uri "https://raw.githubusercontent.com/$Repo/$Branch/version.txt" -Headers @{'User-Agent'='HVMC-Updater'} -TimeoutSec 20)).Trim();Write-Log "HVMC versie: $remoteVersion";$tracked=New-Object 'System.Collections.Generic.List[string]';SyncTree 'content' $MinecraftDir $tracked;$old=ReadJson $ManagedPath;$oldFiles=if($old-and$old.files){@($old.files)}else{@()};CleanupOld $oldFiles @($tracked);SaveJson ([pscustomobject]@{files=@($tracked|Sort-Object -Unique);version=$remoteVersion;updated=(Get-Date).ToUniversalTime().ToString('o')}) $ManagedPath;EnsureLauncher|Out-Null;EnsureFabric;SaveJson ([pscustomobject]@{installedVersion=$remoteVersion;updated=(Get-Date).ToUniversalTime().ToString('o')}) $StatePath;Write-Log 'HVMC update/installatie voltooid.';exit 0}catch{Write-Log "Updater mislukt: $($_.Exception.Message)";exit 1}finally{Write-Log 'HVMC updater afgerond.'}
